### ISSUE TITLE
Background issue

### ISSUE THREAD

**Issue by elecro** [WebKitNix/webkitnix#11]
After the fed1c357521818a1e5ba9344f12aece6bff013ad commit if a page does not have background color set (like the layout results page) then the background will be black and all messed up if scrolling or opening another page.

Maybe we could revert this change?

**Comment by setanta** [comment]
Yep, it will be reverted.
Later I will check why this seemingly innocent change causes this.

**Comment by dakerfp** [comment]
Reverted in: c13eace3090f15224dc7eb60546f435a78be1b1d
