### ISSUE TITLE
ASSERT_WITH_SECURITY_IMPLICATION FAILED: !object || object->isMeter() in WebCore::toRenderMeter

### ISSUE THREAD

**Issue by renatahodovan** [WebKitNix/webkitnix#15]
The condition ASSERT_WITH_SECURITY_IMPLICATION(!object || object->isMeter()) in WebCore::toRenderMeter fails on the following test:

`<html>
    <div style="-webkit-appearance: rating-level-indicator;">
        <fieldset></fieldset>
    </div>
</html>`

This assertion check was introduced in r140640. According to the comments probably we made a bad cast mistake somewhere. Furthermore it seems that the problem is nix-specific.

**Comment by jeez** [comment]
At a first glance, I couldn't find we using it, but I guess @dakerfp knows about it better.

**Comment by qrwteyrutiyoup** [comment]
This should solve it https://gist.github.com/qrwteyrutiyoup/5850304, but the guys are having a holiday today, so probably it won' t be reviewed until tomorrow.

**Comment by qrwteyrutiyoup** [comment]
Thanks for reporting this problem. Closing the issue as ffa508e has landed.
