### ISSUE TITLE
Next merge build issues

### ISSUE THREAD

**Issue by elecro** [WebKitNix/webkitnix#32]
Hi!

Just a heads up for the person who will do the next merge:

I did a little work ahead and did a merge form the webkit trunk. The merge was ok (on 2013.10.16), but there were build fails related to the fact that PlatformCertificateInfo was moved to the WebCore and renamed to CertificateInfo. Anyways I did 2 patches to fix these issues:
- One for the soup build: https://gist.github.com/elecro/a961defe1f157e8299b0
- One for the curl build: https://gist.github.com/elecro/92dd5d6f06636a7c7487

**Comment by thiagolacerda** [comment]
Great :)

They are in the merge commit, today

Cheers

On Fri, Oct 18, 2013 at 4:34 AM, elecro notifications@github.com wrote:

> Hi!
> 
> Just a heads up for the person who will do the next merge:
> 
> I did a little work ahead and did a merge form the webkit trunk. The merge
> was ok (on 2013.10.16), but there were build fails related to the fact that
> PlatformCertificateInfo was moved to the WebCore and renamed to
> CertificateInfo. Anyways I did 2 patches to fix these issues:
> - One for the soup build:
>   https://gist.github.com/elecro/a961defe1f157e8299b0
> - One for the curl build:
>   https://gist.github.com/elecro/92dd5d6f06636a7c7487
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WebKitNix/webkitnix/issues/32
> .

## 

Thiago de Barros Lacerda
OpenBossa - INdT
